build:
  module: es2015
  moduleName: apiGenerator
config:
  baseURL: ''
  method: get
  headers: {}
  timeout: 5000
  requestFormat: origin
  responseEncoding: utf8
  responseType: json
  succCond: {}
  succRsp: null
  failRsp: null
  withCredentials: false
